#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright Authors of Tetragon

set -euo pipefail

agent_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
env_file=$agent_dir/build/java-monitoring.env
app_dir=${PETCLINIC_DIR:-$agent_dir/build/apps/spring-petclinic}
maven_cache=${PETCLINIC_MAVEN_CACHE:-$agent_dir/build/maven-cache}
petclinic_ref=${PETCLINIC_REF:-main}
pin_path=/sys/fs/bpf/tetragon/tg_java_urb

if [[ ! -f $env_file ]]; then
	echo "Missing $env_file" >&2
	echo "Run $agent_dir/run-tetragon.sh first." >&2
	exit 1
fi

# The file is generated by run-tetragon.sh and contains shell-escaped paths.
# shellcheck disable=SC1090
source "$env_file"

if ! sudo test -e "$pin_path"; then
	echo "The Java producer map is not available at $pin_path" >&2
	echo "Keep run-tetragon.sh running in another terminal and retry." >&2
	exit 1
fi
if ! command -v git >/dev/null 2>&1 || ! command -v docker >/dev/null 2>&1; then
	echo "run-petclinic.sh requires git and Docker." >&2
	exit 1
fi

mkdir -p -- "$(dirname -- "$app_dir")" "$maven_cache"
if [[ ! -d $app_dir/.git ]]; then
	echo "Cloning Spring PetClinic ($petclinic_ref)"
	git clone --depth 1 --branch "$petclinic_ref" \
		https://github.com/spring-projects/spring-petclinic.git "$app_dir"
else
	echo "Using existing Spring PetClinic checkout at $app_dir"
fi

echo "Building Spring PetClinic with $JAVA_MONITOR_JDK_IMAGE"
docker run --rm \
	--network=host \
	--user "$(id -u):$(id -g)" \
	-e HOME=/tmp \
	-v "$app_dir:/app" \
	-v "$maven_cache:/maven-cache" \
	-w /app \
	"$JAVA_MONITOR_JDK_IMAGE" \
	./mvnw --no-transfer-progress -Dmaven.repo.local=/maven-cache \
	-Dmaven.test.skip=true package

petclinic_jar=$(find "$app_dir/target" -maxdepth 1 -type f \
	-name 'spring-petclinic-*.jar' ! -name '*.original' | sort | head -n 1)
if [[ -z $petclinic_jar ]]; then
	echo "Spring PetClinic build did not produce an executable jar." >&2
	exit 1
fi

monitor_class=${JAVA_MONITOR_CLASS-org.springframework.samples.petclinic.owner.OwnerController}
monitor_method=${JAVA_MONITOR_METHOD-showOwner}
agent_argument="class=$monitor_class,method=$monitor_method"

echo "Starting Spring PetClinic on http://localhost:8080"
echo "Monitoring ${monitor_class:-*}#${monitor_method:-*}"
echo "Generate events with: curl http://localhost:8080/owners/1"

# ASM is appended to the bootstrap search path because java -jar otherwise
# ignores an application class path. Host PID visibility is required because
# the prototype does not translate container PID namespaces.
exec sudo docker run --rm --privileged --pid=host --network=host \
	-v /sys/fs/bpf:/sys/fs/bpf \
	-v "$JAVA_MONITOR_AGENT_DIR:/agent:ro" \
	-v "$JAVA_MONITOR_ASM_JAR:/deps/asm.jar:ro" \
	-v "$JAVA_MONITOR_ASM_COMMONS_JAR:/deps/asm-commons.jar:ro" \
	-v "$petclinic_jar:/app/petclinic.jar:ro" \
	"$JAVA_MONITOR_JDK_IMAGE" \
	java --enable-native-access=ALL-UNNAMED \
	-Xbootclasspath/a:/deps/asm.jar:/deps/asm-commons.jar \
	"-javaagent:/agent/tetragon-java-monitoring-agent.jar=$agent_argument" \
	-jar /app/petclinic.jar "$@"
