apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "kill-syscalls"
spec:
  list:
    - name: "list_int"
      type: "int"
      values:
        - 0
          1
          2
          3
    - name: "list_string"
      type: "string"
      values:
        - "elem0"
          "elem1"
          "elem2"
          "elem3"
    - name: "list_syscalls"
      type: "syscalls"
      values:
        - "sys_read"
          "sys_write"
  killer:
    - syscalls:
      - list: "list_syscall"
  tracepoints:
    - subsystem: "raw_syscalls"
      event: "sys_enter"
      args:
        - index: 4
          type: "uint64"
      selectors:
      - matchArgs:
        - index: 0
          list: "list_syscalls"
      - matchActions:
        - action: NotifyKiller
