apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "kill-syscalls"
spec:
  killers:
  - syscalls:
    - "sys_prctl"
  tracepoints:
  - subsystem: "raw_syscalls"
    event: "sys_enter"
    args:
    - index: 4
      type: "uint64"
    selectors:
    - matchArgs:
      - index: 0
        operator: "InRefMap"
        values:
        - "ref:killer"
      matchActions:
      - action: "NotifyKiller"
