apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sysftruncate"
# reproduce:
#   truncate -s 0 /tmp/passwd
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: "file"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/tmp/passwd"
      matchActions:
      - action: FollowFD
        argFd: 0
        argName: 1
  - call: "sys_close"
    syscall: true
    args:
    - index: 0
      type: "int"
    selectors:
    - matchActions:
      - action: UnfollowFD
        argFd: 0
        argName: 0
  - call: "sys_ftruncate"
    syscall: true
    args:
    - index: 0
      type: "fd"
    - index: 1
      type: "size_t"
    selectors:
    - matchPIDs:
      - operator: NotIn
        values:
        - 0
        - 1
      matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/tmp/passwd"
      matchActions:
      - action: Override
        argError: -1
      - action: SigKill
