apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "uprobe"
spec:
  uprobes:
  - path: "/usr/lib/x86_64-linux-gnu/libc.so.6"
    symbol: "malloc"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/bin/bash"
  - path: "/usr/lib/x86_64-linux-gnu/libc.so.6"
    symbol: "free"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/bin/bash"
